version: "3.8"

services: 
  server:
    # image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    ports: 
      - '8000:80'
    volumes: 
      - ./src:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on: 
      - php
      - mysql
      - npm
      - phpmyadmin
  php:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    tty: true
    volumes: 
      - ./src:/var/www/html:delegated
  mysql:
    image: mysql:5.7
    ports:
      - '3308:3308'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: 
      - ./env/mysql.env
  phpmyadmin:
    depends_on: 
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment: 
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret
  composer:
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes: 
      - ./src:/var/www/html
  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes: 
      - ./src:/var/www/html
    entrypoint: ["php", "/var/www/html/artisan"]
  npm:
    image: node:14
    working_dir: /var/www/html
    entrypoint: ["npm"]
    volumes: 
      - ./src:/var/www/html
volumes:
    db_data: {}
